import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import GeneralProvider from "@/components/Provider";

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <AntdRegistry>
        <GeneralProvider>{children}</GeneralProvider>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
